# Generated by Django 4.0.5 on 2022-06-09 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField()),
                ('name', models.CharField(max_length=40)),
                ('branch', models.CharField(max_length=40)),
                ('photo', models.ImageField(upload_to='')),
                ('dmc', models.FileField(upload_to='')),
            ],
        ),
    ]
