# Generated by Django 4.0.5 on 2022-06-12 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dmc',
            field=models.FileField(blank=True, upload_to='dmcs'),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, upload_to='pic'),
        ),
    ]
